export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_CARTS = "FETCH_CARTS";
export const ADD_TO_CART = "ADD_TO_CART";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
